export type Keyword = { term: string; definition: string };

export const KEYWORDS: Record<string, Keyword[]> = {
  starter: [
    { term: "Program", definition: "A set of instructions that a computer follows." },
    { term: "Statement", definition: "One complete instruction in a program." },
    { term: "Variable", definition: "A named place used to store a value that the program can use or change." },
    { term: "String", definition: "Text, such as a name or message. In Python, string values use quotation marks." },
    { term: "Syntax", definition: "The rules for writing code so that Python can understand it." },
    { term: "Run", definition: "Ask Python to execute the program from the first line onwards." },
  ],
  input: [
    { term: "Input", definition: "Data that enters a program, often typed by a user." },
    { term: "Output", definition: "Information that a program displays, saves or sends out." },
    { term: "String", definition: "Text. Python input begins as a string unless you convert it." },
    { term: "Integer", definition: "A whole number, such as -3, 0 or 25." },
    { term: "Float", definition: "Python's name for a number that can contain a decimal point, such as 12.5." },
    { term: "Conversion", definition: "Changing a value from one data type to another, such as text to an integer." },
  ],
  selection: [
    { term: "Selection", definition: "Choosing which instructions run according to a condition." },
    { term: "Condition", definition: "A test that has the result True or False." },
    { term: "Boolean", definition: "A data type with only two possible values: True or False." },
    { term: "if", definition: "Runs an indented block when its condition is True." },
    { term: "elif", definition: "Tests another condition when the earlier condition was False." },
    { term: "else", definition: "Runs when none of the earlier conditions were True." },
  ],
  loops: [
    { term: "Iteration", definition: "Repeating a set of instructions. It is also called looping." },
    { term: "FOR loop", definition: "Repeats a known number of times or once for each item." },
    { term: "WHILE loop", definition: "Repeats while a condition remains True." },
    { term: "range()", definition: "Creates the number sequence used by many Python FOR loops. Its stop value is not included." },
    { term: "Counter", definition: "A variable that records how many times something has happened." },
    { term: "Accumulator", definition: "A variable that builds a running total." },
  ],
  lists: [
    { term: "List", definition: "Several values stored together under one variable name." },
    { term: "Element", definition: "One item stored inside a list." },
    { term: "Index", definition: "The position used to access an item. Python's first index is 0." },
    { term: "append()", definition: "Adds one new item to the end of a Python list." },
    { term: "len()", definition: "Returns the number of items in a string, list or other collection." },
  ],
  grids: [
    { term: "2D list", definition: "A list containing other lists, commonly used to represent rows and columns." },
    { term: "Row", definition: "A horizontal group of values in a 2D structure." },
    { term: "Column", definition: "A vertical group of values in a 2D structure." },
    { term: "Nested loop", definition: "A loop placed inside another loop. It can visit every cell in a grid." },
    { term: "Cell", definition: "One value at a particular row and column position." },
  ],
  subroutines: [
    { term: "Subroutine", definition: "A named section of code that performs one clear job. It is also called a module." },
    { term: "Procedure", definition: "A subroutine called to perform an action. It does not have to return a value." },
    { term: "Function", definition: "A subroutine that returns a value to the part of the program that called it." },
    { term: "Parameter", definition: "A named input shown in a subroutine's definition." },
    { term: "Argument", definition: "The actual value supplied when a subroutine is called." },
    { term: "Return value", definition: "The result sent back by a function." },
  ],
  files: [
    { term: "Text file", definition: "A permanent file that stores characters arranged into lines." },
    { term: "Read", definition: "Take existing data from a file without changing it." },
    { term: "Write", definition: "Create or replace file content." },
    { term: "Append", definition: "Add new content to the end of an existing file." },
    { term: "Line", definition: "One section of text ending with a newline character." },
    { term: "Persistent", definition: "Still available after the program stops running." },
  ],
  algorithms: [
    { term: "Algorithm", definition: "A precise sequence of steps for solving a problem." },
    { term: "Linear search", definition: "Checks items one at a time from the beginning until the target is found or the data ends." },
    { term: "Target", definition: "The value a search is trying to find." },
    { term: "Bubble sort", definition: "Repeatedly compares neighbouring items and swaps those in the wrong order." },
    { term: "Pass", definition: "One complete movement through the values being sorted." },
    { term: "Swap", definition: "Exchange the positions of two values." },
  ],
  "problem-solver": [
    { term: "Decomposition", definition: "Breaking one large problem into smaller, manageable modules." },
    { term: "Validation", definition: "Checking that input is sensible and follows the stated rules." },
    { term: "1D list", definition: "A single sequence of values accessed with one index." },
    { term: "2D list", definition: "Rows of values accessed with a row index and a column index." },
    { term: "Parallel lists", definition: "Two lists where values at the same index belong together." },
    { term: "Boundary test", definition: "A test using a value at, just below or just above an allowed limit." },
  ],
  "advanced-as": [
    { term: "Module", definition: "A named, reusable part of a program with one clear responsibility." },
    { term: "Header", definition: "The first line of a procedure or function, containing its name and parameters." },
    { term: "Record", definition: "A group of related fields describing one item, such as one stock product." },
    { term: "Parse", definition: "Break stored text into the separate values that the program needs." },
    { term: "Case-insensitive", definition: "Treat uppercase and lowercase letters as equivalent during a comparison." },
    { term: "Audit", definition: "A systematic check that records what was found." },
  ],
};
